'use client';

import { useState } from 'react';
import { getStoredToken } from '@/lib/spotify/auth';
import { discoverByGenres, createPlaylist } from '@/lib/spotify/api';
import { VibeCluster } from '@/lib/clustering';
import { SpotifyTrack } from '@/lib/spotify/types';
import styles from './GeneratePlaylist.module.css';

interface Props {
  vibe: VibeCluster;
}

export default function GeneratePlaylist({ vibe }: Props) {
  const [discoveries, setDiscoveries] = useState<SpotifyTrack[] | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [savedUrl, setSavedUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const generate = async () => {
    const token = getStoredToken();
    if (!token) return;

    setIsGenerating(true);
    setError(null);
    try {
      const excludeIds = new Set(vibe.tracks.map((t) => t.id));
      const tracks = await discoverByGenres(token, vibe.topGenres, excludeIds, 30);
      if (tracks.length === 0) {
        setError('No new tracks found for this vibe. Try another orbit.');
      } else {
        setDiscoveries(tracks);
      }
    } catch {
      setError('Failed to search for new tracks.');
    } finally {
      setIsGenerating(false);
    }
  };

  const save = async () => {
    const token = getStoredToken();
    if (!token || !discoveries) return;

    setIsSaving(true);
    try {
      const url = await createPlaylist(
        token,
        `${vibe.label} — vyba`,
        `Generated by Vyba from your "${vibe.label}" orbit. ${vibe.description}`,
        discoveries.map((t) => t.uri)
      );
      setSavedUrl(url);
    } catch {
      setError('Failed to save playlist.');
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className={styles.container}>
      {!discoveries ? (
        <>
          <button className={styles.generateBtn} onClick={generate} disabled={isGenerating}>
            {isGenerating ? 'Finding new sounds...' : `Discover more ${vibe.label}`}
          </button>
          {error && <p className={styles.error}>{error}</p>}
        </>
      ) : (
        <>
          <div className={styles.sectionHeader}>
            <h2 className={styles.sectionTitle}>Fresh discoveries</h2>
            {savedUrl ? (
              <a href={savedUrl} target="_blank" rel="noopener noreferrer" className={styles.savedLink}>
                Open in Spotify
              </a>
            ) : (
              <button className={styles.saveBtn} onClick={save} disabled={isSaving}>
                {isSaving ? 'Saving...' : 'Save playlist'}
              </button>
            )}
          </div>
          <div className={styles.trackList}>
            {discoveries.map((track) => (
              <a
                key={track.id}
                href={track.external_urls.spotify}
                target="_blank"
                rel="noopener noreferrer"
                className={styles.trackRow}
              >
                <img
                  src={track.album.images[track.album.images.length - 1]?.url}
                  alt=""
                  className={styles.trackImg}
                  width={44}
                  height={44}
                />
                <div className={styles.trackInfo}>
                  <span className={styles.trackName}>{track.name}</span>
                  <span className={styles.trackArtist}>
                    {track.artists.map((a) => a.name).join(', ')}
                  </span>
                </div>
              </a>
            ))}
          </div>
          <button className={styles.refreshBtn} onClick={generate}>
            Refresh
          </button>
        </>
      )}
    </div>
  );
}
